---
name: "observability-stack"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: unless-stopped
    volumes: 
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    command: 
      - --config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki:/etc/loki

  tempo-init:
    image: grafana/tempo:latest
    container_name: tempo-init
    user: root
    entrypoint:
      - chown
      - 10001:10001
      - /var/tempo
    volumes:
      - tempo_data:/var/tempo

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    ports:
      - 11211:11211
    environment:
      - MEMCACHED_MAX_MEMORY=64m
      - MEMCACHED_THREADS=4

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    ports:
      - 3200:3200  # tempo
      - 9095:9095  # tempo grpc
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
    command:
      - -config.file=/etc/tempo/tempo.yaml
    volumes:
      - tempo_data:/var/tempo
      - ./tempo:/etc/tempo
    depends_on:
      - tempo-init
      - memcached

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:

