---
scrape_configs:
  - job_name: pushgateway
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: [pushgateway:9091]
